backend:
  name: github
  repo: JB-code-bit/JB-code-bit

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "photos"
    label: "Photos"
    folder: "images/uploads"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Category", name: "category", widget: "select", options: ["shirtless","headshots","commercial","fullbody","fashion","other"] }
