name: Upload Portfolio Photo

on:
  repository_dispatch:
    types: [upload-file]

permissions:
  contents: write

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_UPLOAD_TOKEN }}

      - name: Save file
        run: |
          mkdir -p ${{ github.event.client_payload.folder }}
          echo "${{ github.event.client_payload.content }}" | base64 -d > ${{ github.event.client_payload.folder }}/${{ github.event.client_payload.filename }}

      - name: Commit changes
        run: |
          git config --global user.name "portfolio-bot"
          git config --global user.email "bot@github.com"
          git add .
          git commit -m "Uploaded portfolio image"
          git push
